version: '2'

services:
  ros2_control:
    #image: osrf/ros:humble-desktop
    build: .
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspaces/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    user: 1001:1001
